export const tableDataMapping = {
  101: "users.json",
  102: "profiles.json",
  103: "roles.json",
  104: "permissions.json",
  105: "audit_logs.json",
  201: "products.json",
  202: "categories.json",
  203: "brands.json",
  204: "product_reviews.json",
  205: "discounts.json",
  301: "orders.json",
  302: "order_items.json",
  303: "payments.json",
  304: "shipment_tracking.json",
  305: "returns.json",
  401: "stock.json",
  402: "suppliers.json",
  403: "warehouses.json",
  404: "purchase_orders.json",
  405: "inventory_transactions.json",
};

export const columnsMapping = {
  101: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "username", header: "Username" },
    { accessorKey: "email", header: "Email" },
    { accessorKey: "role", header: "Role" },
  ],
  102: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "user_id", header: "User ID" },
    { accessorKey: "full_name", header: "Full Name" },
    { accessorKey: "age", header: "Age" },
    { accessorKey: "country", header: "Country" },
  ],
  103: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "role_name", header: "Role Name" },
  ],
  104: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "permission", header: "Permission" },
    { accessorKey: "role_id", header: "Role ID" },
  ],
  105: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "action", header: "Action" },
    { accessorKey: "timestamp", header: "Timestamp" },
    { accessorKey: "user", header: "User" },
  ],
  201: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "name", header: "Product Name" },
    { accessorKey: "category", header: "Category" },
    { accessorKey: "price", header: "Price" },
  ],
  202: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "category_name", header: "Category Name" },
  ],
  203: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "brand_name", header: "Brand Name" },
  ],
  204: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "product_id", header: "Product ID" },
    { accessorKey: "rating", header: "Rating" },
    { accessorKey: "review", header: "Review" },
  ],
  205: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "product_id", header: "Product ID" },
    { accessorKey: "discount_percent", header: "Discount (%)" },
    { accessorKey: "valid_until", header: "Expiry Date" },
  ],
  301: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "user_id", header: "User ID" },
    { accessorKey: "total_price", header: "Total Amount" },
    { accessorKey: "status", header: "Status" },
  ],
  302: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "order_id", header: "Order ID" },
    { accessorKey: "product_id", header: "Product ID" },
    { accessorKey: "quantity", header: "Quantity" },
  ],
  303: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "order_id", header: "Order ID" },
    { accessorKey: "payment_method", header: "Payment Method" },
    { accessorKey: "status", header: "Status" },
  ],
  304: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "order_id", header: "Order ID" },
    { accessorKey: "tracking_number", header: "Tracking Number" },
    { accessorKey: "status", header: "Status" },
  ],
  305: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "order_id", header: "Order ID" },
    { accessorKey: "reason", header: "Return Reason" },
    { accessorKey: "status", header: "Status" },
  ],
  401: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "product_id", header: "Product ID" },
    { accessorKey: "warehouse_id", header: "Warehouse ID" },
    { accessorKey: "quantity", header: "Quantity Available" },
  ],
  402: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "supplier_name", header: "Supplier Name" },
    { accessorKey: "contact", header: "Contact" },
  ],
  403: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "location", header: "Location" },
    { accessorKey: "capacity", header: "Capacity" },
  ],
  404: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "supplier_id", header: "Supplier ID" },
    { accessorKey: "total_amount", header: "Total Cost" },
    { accessorKey: "status", header: "Status" },
  ],
  405: [
    { accessorKey: "id", header: "ID" },
    { accessorKey: "product_id", header: "Product ID" },
    { accessorKey: "transaction_type", header: "Transaction Type" },
    { accessorKey: "quantity", header: "Quantity Changed" },
  ],
};
